import { useState } from 'react'
import type { ConnectionProfile, DataSourceKind, DataSourceProfile } from '@shared/types'
import { BigQueryConnectionModal } from './BigQueryConnectionModal'
import { LocalFilesConnectionModal } from './LocalFilesConnectionModal'
import { LokiConnectionModal } from './LokiConnectionModal'
import { PostgresConnectionModal } from './PostgresConnectionModal'
import { PrometheusConnectionModal } from './PrometheusConnectionModal'
import { SqliteFileConnectionModal } from './SqliteFileConnectionModal'
import { TempoConnectionModal } from './TempoConnectionModal'
import { CONNECTION_SOURCE_DESCRIPTORS, SourceIcon } from './connectionSources'
import type { ConnectionModalProps } from './connectionFormTypes'
import styles from './ConnectionModal.module.css'

export function ConnectionModal(props: ConnectionModalProps) {
  const [kind, setKind] = useState<DataSourceProfile['kind'] | null>(props.existing?.kind ?? null)
  const [visited, setVisited] = useState<DataSourceKind[]>([])
  if (!props.existing) {
    const select = (next: DataSourceKind) => { setVisited((current) => current.includes(next) ? current : [...current, next]); setKind(next) }
    const onPickerKeyDown = (event: React.KeyboardEvent<HTMLDivElement>) => { if (!['ArrowRight', 'ArrowDown', 'ArrowLeft', 'ArrowUp'].includes(event.key)) return; event.preventDefault(); const cards = Array.from(event.currentTarget.querySelectorAll<HTMLButtonElement>('button:not(:disabled)')); const index = Math.max(0, cards.indexOf(document.activeElement as HTMLButtonElement)); cards[(index + (event.key === 'ArrowRight' || event.key === 'ArrowDown' ? 1 : cards.length - 1)) % cards.length]?.focus() }
    return <>{!kind && <div className={[styles.modalOverlay].join(' ')} onClick={props.onClose}><div className={[styles.modal, styles.connectionPicker].join(' ')} role="dialog" aria-modal="true" aria-labelledby="connection-picker-title" onClick={(event) => event.stopPropagation()}><div className={[styles.wizardSteps].join(' ')}>Step 1 of 2 · Source</div><h2 id="connection-picker-title">Choose a connection type</h2><p className={[styles.connectionPickerIntro].join(' ')}>Select where your data lives. You can return here before saving.</p><div className={[styles.connectionSourceGrid].join(' ')} role="radiogroup" aria-label="Connection types" onKeyDown={onPickerKeyDown}>{CONNECTION_SOURCE_DESCRIPTORS.map((source, index) => { const disabled = !source.supportsCreate; return <button key={source.kind} type="button" role="radio" aria-checked="false" aria-disabled={disabled} disabled={disabled} tabIndex={disabled ? -1 : index === 0 ? 0 : -1} className={[styles.connectionSourceCard].join(' ')} onClick={() => !disabled && select(source.kind as DataSourceKind)}><span className={[styles.sourceIcon].join(' ')}><SourceIcon type={source.icon} /></span><span className={[styles.sourceCardCopy].join(' ')}><strong>{source.label}</strong><span>{source.description}</span><small>{source.hint}</small></span></button> })}</div><div className={[styles.actions].join(' ')}><button type="button" className={['btn', 'ghost'].join(' ')} onClick={props.onClose}>Cancel</button></div></div></div>}{visited.map((item) => <div key={item} className={kind === item ? undefined : styles.wizardFormHidden} aria-hidden={kind !== item}>{item === 'postgres' ? <PostgresConnectionModal {...props} existing={null} active={kind === item} onBack={() => setKind(null)} /> : item === 'local-files' ? <LocalFilesConnectionModal {...props} existing={null} active={kind === item} onBack={() => setKind(null)} /> : item === 'sqlite-file' ? <SqliteFileConnectionModal {...props} existing={null} active={kind === item} onBack={() => setKind(null)} /> : item === 'bigquery' ? <BigQueryConnectionModal {...props} existing={null} active={kind === item} onBack={() => setKind(null)} /> : item === 'tempo' ? <TempoConnectionModal {...props} existing={null} active={kind === item} onBack={() => setKind(null)} /> : item === 'loki' ? <LokiConnectionModal {...props} existing={null} active={kind === item} onBack={() => setKind(null)} /> : <PrometheusConnectionModal {...props} existing={null} active={kind === item} onBack={() => setKind(null)} />}</div>)}</>
  }
  return props.existing.kind === 'local-files' ? <LocalFilesConnectionModal {...props} existing={props.existing} /> : props.existing.kind === 'sqlite-file' ? <SqliteFileConnectionModal {...props} existing={props.existing} /> : props.existing.kind === 'bigquery' ? <BigQueryConnectionModal {...props} existing={props.existing} /> : props.existing.kind === 'prometheus' ? <PrometheusConnectionModal {...props} existing={props.existing} /> : props.existing.kind === 'tempo' ? <TempoConnectionModal {...props} existing={props.existing} /> : props.existing.kind === 'loki' ? <LokiConnectionModal {...props} existing={props.existing} /> : <PostgresConnectionModal {...props} existing={props.existing as ConnectionProfile} />
}
