import { useEffect, useState } from 'react'
import type { PrometheusProfile } from '@shared/types'
import type { PrometheusDatasourceOption } from '@shared/prometheus'
import { normalizeGrafanaBaseUrl } from '@shared/grafanaExplore'
import { api } from '@lib/api'
import { Combobox } from '@components/ui/combobox'
import { TextInput } from '@components/ui/TextInput'
import { CollapsibleSection } from '@components/ui/CollapsibleSection'
import { ConnectionFormHeader } from './ConnectionFormHeader'
import type { ConnectionFormProps } from './connectionFormTypes'
import { failureMessage } from './connectionFormTypes'
import styles from './ConnectionModal.module.css'

export function PrometheusConnectionModal({ existing, onClose, onSaved, onBack }: ConnectionFormProps & { existing: PrometheusProfile | null }) {
  const [name, setName] = useState(existing?.name ?? 'Prometheus'); const [message, setMessage] = useState<{ ok: boolean; text: string } | null>(null); const [gcxVersion, setGcxVersion] = useState<string | null>(null); const [datasources, setDatasources] = useState<PrometheusDatasourceOption[]>([]); const [datasourceUid, setDatasourceUid] = useState(existing?.transport.datasourceUid ?? ''); const [datasourceError, setDatasourceError] = useState<string | null>(null); const [loadingDatasources, setLoadingDatasources] = useState(true); const [busy, setBusy] = useState(false)
  const [grafanaUrl, setGrafanaUrl] = useState(existing?.grafana?.baseUrl ?? ''); const [orgId, setOrgId] = useState(String(existing?.grafana?.orgId ?? 1))
  const baseTransport = () => ({ kind: 'gcx' as const, ...(existing?.transport.context ? { context: existing.transport.context } : {}) }); const transport = () => ({ ...baseTransport(), ...(datasourceUid ? { datasourceUid } : {}) })
  const selected = datasources.find((item) => item.uid === datasourceUid)
  const grafana = () => grafanaUrl.trim() ? { baseUrl: normalizeGrafanaBaseUrl(grafanaUrl), orgId: Number(orgId), datasourceType: selected?.type ?? existing?.grafana?.datasourceType } : undefined
  const profile = (): PrometheusProfile => ({ kind: 'prometheus', version: 1, id: existing?.id ?? '', name: name.trim(), readonly: true, transport: transport(), ...(grafana() ? { grafana: grafana() } : {}) })
  useEffect(() => { let active = true; setLoadingDatasources(true); api.connections.prometheus.discoverDatasources(baseTransport()).then((found: PrometheusDatasourceOption[]) => { if (!active) return; setDatasources(found); setDatasourceUid((current) => current || (found.length === 1 ? found[0].uid : '')); setDatasourceError(found.length ? null : 'No compatible Prometheus or Mimir datasources were found.') }).catch((error: unknown) => { if (active) setDatasourceError(failureMessage(error)) }).finally(() => { if (active) setLoadingDatasources(false) }); return () => { active = false } }, [])
  const validate = () => { if (!name.trim()) return 'Connection name is required.'; if (!datasourceUid) return 'Select a Prometheus datasource first.'; if (grafanaUrl.trim()) { try { normalizeGrafanaBaseUrl(grafanaUrl) } catch (error) { return failureMessage(error) }; if (!/^\d+$/.test(orgId) || Number(orgId) < 1) return 'Grafana org ID must be a positive integer.'; if (!selected?.type && !existing?.grafana?.datasourceType) return 'Rediscover the datasource to configure Grafana handoff.' } return null }
  const test = async () => { const error = validate(); if (error) return setMessage({ ok: false, text: error }); setBusy(true); setMessage(null); try { const result = await api.connections.prometheus.discover(transport()); setGcxVersion(result.gcx?.version ?? null); setMessage({ ok: true, text: `Connected — discovered ${result.metricNames.length} metrics${result.metadataAvailable ? ' with metadata' : ''}.` }) } catch (error) { setMessage({ ok: false, text: failureMessage(error) }) } finally { setBusy(false) } }
  const save = async () => { const error = validate(); if (error) return setMessage({ ok: false, text: error }); setBusy(true); try { const saved = await api.connections.upsert(profile()); onSaved(saved); onClose() } catch (error) { setMessage({ ok: false, text: failureMessage(error) }); setBusy(false) } }
  return <div className={styles.modalOverlay} onClick={onClose}><div className={styles.modal} role="dialog" aria-modal="true" aria-labelledby="prometheus-connection-title" onClick={(e) => e.stopPropagation()}><ConnectionFormHeader kind="prometheus" editing={!!existing} onBack={onBack} /><div className={styles.field}><TextInput label="Connection name" id="prom-name" value={name} onValueChange={setName} /></div><div className={styles.field}><label>Connection method</label><div className={styles.connPreview}>Grafana Cloud via gcx</div></div><div className={styles.field}><Combobox id="prom-datasource" label="Prometheus datasource" value={datasourceUid} onChange={setDatasourceUid} disabled={loadingDatasources} loading={loadingDatasources} placeholder="Select a datasource" options={datasources.map((datasource) => ({ value: datasource.uid, label: datasource.name }))} />{datasourceError && <div className={styles.pasteHint} role="alert">{datasourceError}</div>}</div><CollapsibleSection title="Grafana handoff override (optional)"><div className={styles.advancedFields}><TextInput label="Grafana base URL override" value={grafanaUrl} onValueChange={setGrafanaUrl} placeholder="https://example.com/grafana" hint="Leave blank to resolve from the selected gcx context. Navigation only; queries still run through gcx." /><TextInput label="Grafana org ID" inputMode="numeric" value={orgId} onValueChange={setOrgId} /></div></CollapsibleSection><div className={[styles.testMsg, styles.info].join(' ')}>Uses your existing authenticated gcx context. DataKoala never reads, copies, or stores gcx OAuth credentials.{gcxVersion && <> Detected <strong>gcx {gcxVersion}</strong>.</>}</div>{message && <div className={[styles.testMsg, message.ok ? styles.ok : styles.err].join(' ')} role={message.ok ? 'status' : 'alert'}>{message.text}</div>}<div className={styles.actions}><button type="button" className="btn ghost" onClick={() => void test()} disabled={busy}>{busy ? 'Working…' : 'Test & discover metrics'}</button><button type="button" className="btn ghost" onClick={onClose}>Cancel</button><button type="button" className="btn primary" onClick={() => void save()} disabled={busy}>Save</button></div></div></div>
}
