import { useEffect, useMemo, useRef, useState } from 'react'
import { useVirtualizer } from '@tanstack/react-virtual'
import type { LokiLogRow } from '@shared/loki'
import styles from './LokiExplorer.module.css'

export function LogResultExplorer({ rows, truncated, limit, onFilter, onCorrelate }: { rows: LokiLogRow[]; truncated?: boolean; limit: number; onFilter: (kind: 'label' | 'field', key: string, value: string, exclude: boolean) => void; onCorrelate?: (traceId: string) => void }) {
  const [search, setSearch] = useState(''); const [expanded, setExpanded] = useState<Set<string>>(new Set()); const parent = useRef<HTMLDivElement>(null)
  const visible = useMemo(() => { const term = search.toLowerCase(); return term ? rows.filter((row) => row.line.toLowerCase().includes(term) || JSON.stringify([row.labels, row.structuredMetadata, row.parsedFields]).toLowerCase().includes(term)) : rows }, [rows, search])
  const virtual = useVirtualizer({ count: visible.length, getScrollElement: () => parent.current, estimateSize: (index) => expanded.has(visible[index]?.id ?? '') ? 250 : 44, overscan: 8 })
  useEffect(() => virtual.measure(), [expanded, virtual])
  const fields = (record: Record<string, unknown>, kind: 'label' | 'field') => <dl>{Object.entries(record).map(([key, value]) => <div key={key}><dt>{key}</dt><dd>{String(value)} <button onClick={() => navigator.clipboard.writeText(String(value))}>Copy</button> <button onClick={() => onFilter(kind, key, String(value), false)}>Include</button> <button onClick={() => onFilter(kind, key, String(value), true)}>Exclude</button></dd></div>)}</dl>
  return <section className={styles.logs} aria-label="Log results"><div className={styles.resultToolbar}><input aria-label="Search loaded logs" placeholder="Search loaded results" value={search} onChange={(event) => setSearch(event.target.value)} /><span>{visible.length} loaded{truncated ? ` · limited to ${limit}; more available` : ''}</span></div>{!visible.length ? <div className={styles.empty}>No log entries found.</div> : <div ref={parent} className={styles.logScroller}><div style={{ height: virtual.getTotalSize(), position: 'relative' }}>{virtual.getVirtualItems().map((item) => { const row = visible[item.index]; const open = expanded.has(row.id); return <article key={row.id} ref={virtual.measureElement} data-index={item.index} className={styles.logRow} style={{ transform: `translateY(${item.start}px)` }}><button className={styles.logSummary} onClick={() => setExpanded((current) => { const next = new Set(current); if (next.has(row.id)) next.delete(row.id); else next.add(row.id); return next })}><time>{new Date(row.timestampMs).toISOString()}</time><strong data-severity={row.severity}>{row.severity}</strong><span>{row.line}</span></button>{open && <div className={styles.logDetails}><div className={styles.logActions}><button onClick={() => navigator.clipboard.writeText(row.line)}>Copy line</button>{row.traceId && <button onClick={() => onCorrelate?.(row.traceId!)}>Open trace {row.traceId}</button>}</div><section><h4>Indexed labels</h4>{fields(row.labels, 'label')}</section><section><h4>Structured metadata</h4>{fields(row.structuredMetadata, 'field')}</section><section><h4>Parsed fields</h4>{fields(row.parsedFields, 'field')}</section></div>}</article> })}</div></div>}</section>
}
