import { useEffect, useMemo, useRef, useState } from 'react'
import { useVirtualizer } from '@tanstack/react-virtual'
import type { LokiLogRow } from '@shared/loki'
import styles from './LokiExplorer.module.css'

const shortTimestamp = (timestampMs: number) => new Intl.DateTimeFormat('en-GB', { hour: '2-digit', minute: '2-digit', second: '2-digit', fractionalSecondDigits: 3, hour12: false, timeZone: 'UTC' }).format(timestampMs)

export function LogResultExplorer({ rows, truncated, limit, onFilter, onCorrelate, correlationDisabledReason }: { rows: LokiLogRow[]; truncated?: boolean; limit: number; onFilter: (kind: 'label' | 'field', key: string, value: string, exclude: boolean) => void; onCorrelate?: (traceId: string) => void; correlationDisabledReason?: string }) {
  const [search, setSearch] = useState(''), [expanded, setExpanded] = useState<Set<string>>(new Set())
  const parent = useRef<HTMLDivElement>(null)
  const visible = useMemo(() => { const term = search.toLowerCase(); return term ? rows.filter((row) => row.line.toLowerCase().includes(term) || JSON.stringify([row.labels, row.structuredMetadata, row.parsedFields]).toLowerCase().includes(term)) : rows }, [rows, search])
  const virtual = useVirtualizer({ count: visible.length, getScrollElement: () => parent.current, estimateSize: (index) => expanded.has(visible[index]?.id ?? '') ? 157 : 42, overscan: 8 })
  useEffect(() => virtual.measure(), [expanded, virtual])
  const fields = (record: Record<string, unknown>, kind: 'label' | 'field') => <dl>{Object.entries(record).map(([key, value]) => <div className={styles.fieldRow} key={key}><dt>{key}</dt><dd>{String(value)}</dd><div className={styles.fieldActions} aria-label={`${key} actions`}><button title={`Copy ${key}`} aria-label={`Copy ${key}`} onClick={() => navigator.clipboard.writeText(String(value))}>Copy</button><button title={`Include ${key}`} aria-label={`Include ${key}`} onClick={() => onFilter(kind, key, String(value), false)}>Include</button><button title={`Exclude ${key}`} aria-label={`Exclude ${key}`} onClick={() => onFilter(kind, key, String(value), true)}>Exclude</button></div></div>)}</dl>
  return <section className={styles.logs} aria-label="Log results"><div className={styles.resultToolbar}><input aria-label="Search loaded logs" placeholder="Search loaded logs…" value={search} onChange={(event) => setSearch(event.target.value)} /><span>{visible.length} loaded{truncated ? ` · limited to ${limit} · more available` : ''}</span></div>{!visible.length ? <div className={styles.empty}>No matching log entries.</div> : <div ref={parent} className={styles.logScroller}><div style={{ height: virtual.getTotalSize(), position: 'relative' }}>{virtual.getVirtualItems().map((item) => { const row = visible[item.index], open = expanded.has(row.id), iso = new Date(row.timestampMs).toISOString(); return <article key={row.id} ref={virtual.measureElement} data-index={item.index} data-expanded={open} className={styles.logRow} style={{ transform: `translateY(${item.start}px)` }}><button className={styles.logSummary} aria-expanded={open} onClick={() => setExpanded((current) => { const next = new Set(current); next.has(row.id) ? next.delete(row.id) : next.add(row.id); return next })}><time dateTime={iso} title={iso}>{shortTimestamp(row.timestampMs)}</time><strong data-severity={row.severity.toUpperCase()}>{row.severity.toUpperCase()}</strong><span>{row.line}</span></button>{open && <div className={styles.logDetails}><div className={styles.logActions}><button className="btn ghost" onClick={() => navigator.clipboard.writeText(row.line)}>Copy line</button>{row.traceId && <button className="btn ghost" onClick={() => onCorrelate?.(row.traceId!)} disabled={!onCorrelate} title={!onCorrelate ? correlationDisabledReason : undefined}>Open trace</button>}{row.traceId && !onCorrelate && <span title={correlationDisabledReason} className={styles.trendLabel}>Trace correlation coming soon</span>}</div><section className={styles.detailSection}><h3>Indexed labels</h3>{fields(row.labels, 'label')}</section><section className={styles.detailSection}><h3>Structured metadata</h3>{fields(row.structuredMetadata, 'field')}</section><section className={styles.detailSection}><h3>Parsed fields</h3>{fields(row.parsedFields, 'field')}</section></div>}</article> })}</div></div>}</section>
}
