import assert from 'node:assert/strict'
import test from 'node:test'
import { clusterLogPatterns, type LogPatternRecord } from './log-patterns.ts'
const records = (...messages: string[]): LogPatternRecord[] => messages.map((message, i) => ({ id: String(i), message, timestampMs: 100 + i, severity: i ? 'error' : 'info' }))
test('normalizes common high-cardinality values', () => { assert.equal(clusterLogPatterns(records('Request 123 completed', 'Request 456 completed')).length, 1); assert.equal(clusterLogPatterns(records('At 2026-01-01T10:20:30Z ip 10.2.3.4 id 550e8400-e29b-41d4-a716-446655440000', 'At 2026-02-02T11:21:31Z ip 10.3.4.5 id 123e4567-e89b-42d3-a456-426614174000')).length, 1) })
test('clusters identifiers without merging semantic actions', () => { assert.equal(clusterLogPatterns(records('Failed to process order 12345 for customer abc-17', 'Failed to process order 89231 for customer def-41')).length, 1); assert.equal(clusterLogPatterns(records('Started worker 123', 'Stopped worker 456')).length, 2); assert.equal(clusterLogPatterns(records('Connection accepted for worker 123', 'Connection rejected for worker 456')).length, 2) })
test('discovers an ordinary textual value and retains every sample', () => { const result = clusterLogPatterns(records('User alice failed login from 10.0.0.1', 'User bob failed login from 10.0.0.2')); assert.equal(result.length, 1); assert.equal(result[0].template, 'User <value> failed login from <ip>'); assert.deepEqual(result[0].variables[0].values, ['alice', 'bob']) })
test('does not match typed placeholders with incompatible values', () => { assert.equal(clusterLogPatterns(records('Operation completed in 123ms', 'Operation completed in failed')).length, 2); assert.equal(clusterLogPatterns(records('Request id 123 completed successfully now', 'Request id abc completed successfully now')).length, 2) })
test('is deterministic and reports metadata', () => { const input = records('Request 123 completed', 'Request 456 completed'), first = clusterLogPatterns(input); assert.deepEqual(first, clusterLogPatterns(input)); assert.equal(first[0].count, 2); assert.equal(first[0].percentage, 100); assert.deepEqual(first[0].memberIds, ['0', '1']); assert.deepEqual(first[0].severities, { info: 1, error: 1 }); assert.equal(first[0].firstTimestampMs, 100); assert.equal(first[0].lastTimestampMs, 101) })
test('handles 5,000 records', () => { const input = Array.from({ length: 5000 }, (_, i) => ({ id: String(i), message: `Processed order ${i} in ${i % 50}ms`, timestampMs: i })); assert.equal(clusterLogPatterns(input).reduce((sum, cluster) => sum + cluster.count, 0), 5000) })
test('keeps patterns reachable beyond a former fixed candidate limit', () => { const word = (i: number) => `kind${String.fromCharCode(97 + Math.floor(i / 26))}${String.fromCharCode(97 + i % 26)}`; const input = Array.from({ length: 80 }, (_, i) => ({ id: String(i), message: `${word(i)} event remained an entirely unique phrase`, timestampMs: i })); input.push({ id: 'repeat', message: `${word(79)} event remained an entirely unique phrase`, timestampMs: 100 }); const result = clusterLogPatterns(input); assert.equal(result.find(({ template }) => template.startsWith(word(79)))?.count, 2) })
